# Generated by Django 4.1.5 on 2023-01-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0002_category_alter_video_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='date',
        ),
        migrations.AddField(
            model_name='video',
            name='video_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='media/'),
        ),
    ]
